[package]
name = "test-world"
version = "0.2.2"
edition = "2024"
repository = "https://github.com/yehezkieldio/test-world"

[dependencies]

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
